language: ruby
rvm:
 - 2.5.1
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: CnG7GzggBpbVkTpWI7rWxBhzlfAxwCK05mn7uUqnNzqadyRCBmclhaTLB/NzjqsRfTwctmkIdcfTGlPAyEOGDSf8qKZHqHLW1idOSW5us75HnPdA9KGhQh0sXoV8R4GxJrQRhhGUdBaTThftW7nLwJ8Xj5qJFsUMWWFfEsptdTszLMfp2Yjw88QXscGSOMoegIZO/6jCzui5Mx815aXYAxKq56GLZ6tOlK7sYh3f68gguGreO2b0ZlpDBPwQBU1z62HssZhgNmG0IzTvAzJmdTdTfunPPLX+wyBQJqp8k/tQcvIIArmGge8BfZkdADpswRzLrBXmj46seHDr6Td9YP/TExkFFW3gIbzaf4xj1CpQabHd2ZolgcLi/FB5zPKUgOxciyt9a0TV8gjkoV8losxqRnUicfRdF5CPmpnp2pbolmpOcpo4PNNfbCQyjnhS2Pub7UspRztTJlXNGQSiMfEtYZhLObfHNrXk9y9RMDExk5uvOp9OH0SVL7zkIJai4XBMlgTx3B5M7XgbS31HlqwncfAPr/QA24qRd8YAJTqEUyP9oJ6Ur4/8hkyws34BoSlT5CqPzI6/2VGlplUd8rnn57akSMD8hPZ860fbSvQ3kRkpV9tJykQ+ZKoYDdL+M082Ke6qD36GgxILcXhG6pz7vqqQMs3bE3DCFnlJ/Xk=
  app: mighty-ravine-56690
