language: ruby
rvm:
- 2.5.1
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  app: mighty-ravine-56690
  api_key:
    secure: OLaRFYsGC+Ox+ScUSckiPpq11fHlEJ/F4C+ae4BSaaiRBiA9iCiFAJeywaMGfx5jvOu/bq1d1ZOVs1ApeqBURiulQwcDQp23WndU/OIJtc9VG9tCa92tiabheGUGr2VwKGnqZP20apUkjioFEZUaD9SWOIBnalUIwXsJHVtmMOHveGA5hHR1WscsjNnUEj4JZSonRjeQFiMmFzogWVMSt3g4OLxQE3Szq03RNx6nri8A2/CvvJbuDe5m3MWcLArE+kRnj1sCsyhk5+1SrYDw04s3PQCDYYpGU21Danp97G1U1RDprlVxpa6REY2PpiBqYGXiKTsuVloNH6R50CBtsRREOA5XvPIGW3YPnm7w7ee/XxX9+HJTjKMMkcSOwVNWUvkKIvZBxuCkoM8PqYNjuynYx97WVoUWieas4eOoSKYH/cII1OqZiTMrmZX5mMQxh9uyNR4ImeUZo3A4pLuReYLEtXen9IKX8Y78O42bKKTfevughcPCwd/8QmybebcEEM0q2CX+4c0ZHAJS6380kHNoB1d4DBVN7J56FMdpRjwNgx14iVoh0qCbra01lRd8pER7pm2iIKSLNS675cc9JaiPnAd37MlXcHZ4gE2hdw7hriIOGsRxSIpDayZesrL9exgMTtKLRG4egat/5xY7+/9CYNOQDP5NEh9Qy7WPtFw=
