language: ruby
rvm:
- 2.5.1
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  app: mighty-ravine-56690
  api_key:
    secure: 0ZLdzJgLl68yWmsQCYf2bgvAU0ajLQuSohuGLdApInV11lZCqgCfrg8Hj5OvwGQZw22Eh+Hcn5bcCZlWvVPEgSb8B8+15POub184Z5Ph2lP03l7uz9mtwfRfuxw3E0ssJmvBhYglbKpiRQH40PpSBcPp3llgBL+/fvHtX7JNen6WzBjOqnl3sXftxSsGsyOifAnSw+UOemwbLgi/IH8S7XCaziAvrEgNMf/bahh/uz+DV7Wcz/se1siOMDlgA8pqB18kuPAzUZkE2Y1Ka2FIcM0luYCPbc/aQ/bpaTh205ipy9Yc5zWD0ZXjhYrZIPWOSUyBPdDx9VQm+LIpvk69wgRfPYiKHcp9csZfhlEYy54lczm2QYDBKYzf9gIV9JY/JI7jQTusnjowR0xiwHyGWzJaIXobbmQsxBekw7N3tuuRVr6azMOdsqeC42BWyo7pnnu9HFbRJ99wS8ylrBuSSS0soaJPogHo1Sb1ijovxOF7Kj+nlbpDRvfGF1RrHOLYV6m0CUaxr10GopvsC7y1uKX8irSPes0M06s4eqBbsbnHrMJElR9BwelBMcISn+MM6nkuKtRwcIdjdbU6oI2EhKL8hZl4EQBlO8w2kKc6V0rCy286mcaOQVb7jGusUm0C4Ok+zvGoCyBmOgHap/a2jAdc+1ZDThW7lG2p1U08Gmo=
